#!/bin/bash
printf "%o\n" $((0${WATER//e/0}${WATER//w/1}${WATER//a/2}${WATER//t/3}${WATER//r/4} + 0${STIR//s/0}${STIR//t/1}${STIR//i/2}${STIR//r/3})) | while IFS= read -r -n1 c; do printf "%s" "$(printf bestchol | cut -c $((c+1)))"; done
